baseurl = "/"
languageCode = "en-us"
title = "zōkashin"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]


	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.
  #ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Leo Trudel"
	description = "CEO of Zōkashin"

	# The path must be relative to the static folder
	favicon = "hvac.png"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "leo.trudel@zokashin.com"

	# Navigation
	[params.navigation]
		brand = "zōkashin"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			#portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Title"
		subtitle   = "we do cool stuff which is the point of this paragraph"
		buttonText = "Learn more"


	# About section
	[params.about]
		headline    = "Smart Home Solutions for Large-Scale Deployments"
		description = "The market for smart home solutions is expected to reach $165 billion by 2025 as hundreds of millions of home owners choose to invest in convenience, property value, and energy management.  However, multifamily residential and medium-sized commercial buildings, which are too complex for standard smart home solutions but too small for industrial scale automation, have been conspicuously left out of this technological revolution. As a result, they have failed to modernize and continue to stretch their operating budgets while single-family homes and large-scale commercial properties are realizing the benefits of sophisticated building intelligence. <br><br> Zōkashin fills this gap with its smart home-type system designed specifically for large buildings in need of technology-driven management solutions that benefit owners and tenants alike. Whether you want to preserve asset life, improve tenant comfort, manage energy and/or emissions, or integrate workflow, we can help you do so while generating positive ROI."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Platform Features"

        [[params.services.list]]
            icon = "fa-mixcloud"
            title = "Centralized and Distributed Controls"
            description = "Tenants can control their HVAC units from their smartphones, while controls can be also be centralized for commercial deployments."

        [[params.services.list]]
            icon = "fa-mobile"
			      title = "Scheduling"
			      description = "Residential tenants can control runtime schedules while commercial facilities managers can centralize scheduling while allowing authorized employees to adjust temperatures as needed during business hours."
			      
			  [[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Fault detection"
            description = "Our devices will tell you if your HVAC units are behaving abnormally and recommend appropriate courses of action to optimize efficiency and reduce costly equipment failures."

        [[params.services.list2]]
            icon = "fa-bolt"
            title = "Diagnostic Tools"
            description = "Our quality control system uses constantly updating data to fix your problems as fast as lightening."
            
        [[params.services.list2]]
            icon = "fa-bolt"
            title = "Maintenance Integration"
            description = "Predictive, reactive, and user-submitted maintenance requests can be sent directly to your contracted maintenance provider via email or integrated with your current dispatch system."

        [[params.services.list2]]
        icon = "fa-bolt"
        title = "OEM Integration"
        description = "We work directly with your HVAC’s manufacturer to ensure your equipment is running at an optimal level."
            
       [[params.services.list3]]
        icon = "fa-bolt"
        title = "Utility Integration"
        description = "Integrate with your utility for better service and Demand Response revenue."
        
        [[params.services.list3]]
        icon = "fa-bolt"
        title = "Marketplace"
        description = "Find new maintenance service providers for long-term relationships, emergency situations, and anything in between."


       [[params.services.list3]]
        icon = "fa-bolt"
        title = "Ultimate Flexibility"
        description = "Our system interfaces with virtually any kind of HVAC system, is simple to install, and requires no retrofitting."



    # Portfolio modals
	#[params.portfolio.modal]
   #     client = "Client"
    #    date = "Date"
     #   category = "Category"
      #  buttonText = "Close"


	# Contact section
	[params.contact]
		headline = "Contact Us"
		description = "Ready to start your next project with us? That's great! Send us an email and we will get back to you as soon as possible!"
		
  [params.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Your Name"
		  email = "Your Email"
		  message = "Your Message"
		  buttonText = "Send"
			
			
	# Google Maps section
	#= [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
